### ISSUE TITLE
datasets.py  issues?

### ISSUE THREAD

**Issue by bobo0810** [joeylitalien/noise2noise-pytorch#4]
Hello,there may be problems with this place
`raise ValueError('Invalid noise type: {}'.format(noise_type))` 
 should be 
`raise ValueError('Invalid noise type: {}'.format(self.noise_type))`

**Comment by bobo0810** [comment]
@joeylitalien

**Comment by joeylitalien** [comment]
[Fixed](https://github.com/joeylitalien/noise2noise-pytorch/commit/ec96b932ad1dab92daf1c05c5131fb49d2e3503f), thanks!
